services:
  app:
    image: analytics-api:v1
    build:
      dockerfile: Dockerfile
    # environment:
    #   - PORT=8002
    #   - DATABASE_URL=postgresql+psycopg://timescaledb_user:timescaledb_password@db_service:5432/timescaledb_db
    env_file:
      - .env.compose
    ports:
      - "8002:8002"
    command: uvicorn main:app --host 0.0.0.0 --port 8002 --reload
    volumes:
      - ./src:/code:rw
    develop:
      watch:
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: requirements.txt
        - action: rebuild
          path: compose.yaml
  
  #postgresql+psycopg://timescaledb_user:timescaledb_password@db_service:5432/timescaledb_db
  db_service:
    image: timescale/timescaledb:latest-pg17
    environment:
      - POSTGRES_USER=timescaledb_user
      - POSTGRES_PASSWORD=timescaledb_password
      - POSTGRES_DB=timescaledb_db
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - timescaledb_data:/var/lib/postgresql/data

volumes:
  timescaledb_data:

